# Generated by Django 3.2.8 on 2021-10-06 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRut', models.CharField(max_length=30, unique=True)),
                ('userType', models.IntegerField(choices=[(0, 'Admin'), (1, 'Cliente'), (2, 'Profesional')])),
                ('firstName', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
